swagger: "2.0"
info:
  version: "1.0.0"
  title: "Simple API"
  description: "A simple API to say Hello"
basePath: "/"
schemes:
  - "http"
paths:
  /hello:
    get:
      summary: "Returns a greeting message"
      responses:
        200:
          description: "A greeting message"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Hello, World!"
